# Generated by Django 5.0.6 on 2026-02-05 07:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('restaurant', 'Restaurant'), ('delivery', 'Delivery Partner')], max_length=20),
        ),
    ]
